### ISSUE TITLE
https://registry.npmjs.org/i/-/i-0.3.2.tgz no longer available

### ISSUE THREAD

**Issue by tosh001** [angularity/node-angularity#64]
Seems like the package https://registry.npmjs.org/i/-/i-0.3.2.tgz is no longer available according to https://www.npmjs.com/package/i

Could we get npm-shrinkwrap.json updated to use 0.3.3?

**Comment by bholloway** [comment]
Fixed in release [0.4.2](/angularity/node-angularity/releases/tag/0.4.2)
